services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:12345@db:5432/postgres
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: